version: '3.1'

services:

  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: smarthack
      POSTGRES_USER: user
      POSTGRES_PASSWORD: sudo
    ports:
      - "5432:5432"
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - database
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: sudo
    restart: unless-stopped
    volumes:
      - "./servers.json:/pgadmin4/servers.json"
    networks:
      - backend
volumes:
  postgres-data:


networks:
  backend:
    driver: bridge
